"""Watermark detection node for KugelAudio."""

import torch
import logging
from typing import Dict, Any, Tuple

from .base_kugelaudio import BaseKugelAudioNode

logger = logging.getLogger("KugelAudio")


class KugelAudioWatermarkNode(BaseKugelAudioNode):
    """Detect if audio was generated by KugelAudio using watermark."""
    
    def __init__(self):
        super().__init__()
        self.watermark_detector = None
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "audio": ("AUDIO",),
            },
        }
    
    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("result",)
    FUNCTION = "check_watermark"
    CATEGORY = "KugelAudio"
    DESCRIPTION = "Check if audio has KugelAudio watermark"
    
    def check_watermark(
        self,
        audio: Dict[str, Any],
    ) -> Tuple[str]:
        """Check if audio has KugelAudio watermark."""
        try:
            from kugelaudio_open import AudioWatermark
            
            # Extract audio
            if not isinstance(audio, dict) or "waveform" not in audio:
                raise ValueError("Invalid audio input")
            
            waveform = audio["waveform"]
            sample_rate = audio.get("sample_rate", 24000)
            
            # Convert to numpy
            if isinstance(waveform, torch.Tensor):
                audio_np = waveform.cpu().float().numpy()
            else:
                audio_np = waveform
            
            # Handle dimensions
            if audio_np.ndim == 3:  # (batch, channels, samples)
                audio_np = audio_np[0, 0, :]
            elif audio_np.ndim == 2:
                audio_np = audio_np[0, :] if audio_np.shape[0] == 1 else audio_np[:, 0]
            
            # Ensure 1D
            audio_np = audio_np.squeeze()
            
            # Detect watermark
            if self.watermark_detector is None:
                self.watermark_detector = AudioWatermark()
            
            result = self.watermark_detector.detect(audio_np, sample_rate=sample_rate)
            
            # Format result as readable string
            if result.detected:
                status = "Watermark DETECTED"
            else:
                status = "Watermark NOT detected"
            
            confidence_pct = result.confidence * 100
            result_str = f"{status}\nConfidence: {confidence_pct:.1f}%"
            
            return (result_str,)
            
        except Exception as e:
            logger.error(f"Watermark check failed: {e}")
            # Return error message on failure
            return ("Error: Watermark check failed\nConfidence: 0.0%",)
    
    @classmethod
    def IS_CHANGED(cls, audio):
        """Cache key for ComfyUI."""
        if isinstance(audio, dict) and "waveform" in audio:
            waveform = audio["waveform"]
            if isinstance(waveform, torch.Tensor):
                return hash(waveform.sum().item())
        return hash(str(audio))
